# Generated by Django 6.0.2 on 2026-02-19 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='unknown@example.com', max_length=254, unique=True)),
                ('date_of_birth', models.DateField(default='2000-01-01')),
            ],
        ),
    ]
